# 日本語のコメントを OK とする
Style/AsciiComments:
  Enabled: false

# 一行に 120 文字まで書いても OK とする
Metrics/LineLength:
  Max: 120

# クラスをincludeする前にコメントしなくても良い
Documentation:
  Enabled: false

# binディレクトリはincludeを文頭に置かなくてもOK
Style/MixinUsage:
  Description: 'Checks that `include`, `extend` and `prepend` exists at the top level.'
  Enabled: true
  Exclude:
    - 'bin/**/*'
